version: '3.9'
services:
  search-flight:
    build: ./services/search-flight
    container_name: search_flight
    ports:
      - "4000:4000"

  api_gateway:
    build: ./services/api-gateway
    container_name: api_gateway
    ports:
      - "3001:3001"
    depends_on:
      - search-flight

  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - api_gateway
